export const LOAD_CART_REQUEST = "LOAD_CART_REQUEST";
export const LOAD_CART_SUCCESS = "LOAD_CART_SUCCESS";
export const LOAD_CART_FAIL = "LOAD_CART_FAIL";

export const SET_CART_REQUEST = "SET_CART_REQUEST";
export const SET_CART_SUCCESS = "SET_CART_SUCCESS";
export const SET_CART_FAIL = "SET_CART_FAIL";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const GET_ALL_SHOP_OF_CITY_REQUEST = "ADD_TO_CART_REQUEST";
export const GET_ALL_SHOP_OF_CITY_SUCCESS = "ADD_TO_CART_SUCCESS";
export const GET_ALL_SHOP_OF_CITY_FAIL = "ADD_TO_CART_FAIL";

export const INCREASE_PRODUCT_COUNT_SUCCESS='INCREASE_PRODUCT_COUNT_SUCCESS'
export const INCREASE_PRODUCT_COUNT_REQUEST='INCREASE_PRODUCT_COUNT_REQUEST';
export const INCREASE_PRODUCT_COUNT_FAIL='INCREASE_PRODUCT_COUNT_FAIL';

export const DECREASE_PRODUCT_COUNT_SUCCESS='DECREASE_PRODUCT_COUNT_SUCCESS'
export const DECREASE_PRODUCT_COUNT_REQUEST='DECREASE_PRODUCT_COUNT_REQUEST';
export const DECREASE_PRODUCT_COUNT_FAIL='DECREASE_PRODUCT_COUNT_FAIL';



