export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const CREATE_RIDER_REQUEST='CREATE_RIDER_REQUEST';
export const CREATE_RIDER_SUCCESS='CREATE_RIDER_SUCCESS';
export const CREATE_RIDER_FAIL='CREATE_RIDER_FAIL';

export const LOAD_PRODUCT_SELLER_REQUEST = "LOAD_PRODUCT_SELLER_REQUEST";
export const LOAD_PRODUCT_SELLER_SUCCESS = "LOAD_PRODUCT_SELLER_SUCCESS";
export const LOAD_PRODUCT_SELLER_FAIL = "LOAD_PRODUCT_SELLER_FAIL";


export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const LOAD_SHOP_FAIL = "LOAD_SHOP_FAIL";
export const LOAD_SHOP_REQUEST = "LOAD_SHOP_REQUEST";
export const LOAD_SHOP_SUCCESS = "LOAD_SHOP_SUCCESS";



